"""Canonical taxonomies sourced from the V0 feature-space report."""

from __future__ import annotations

CANONICAL_SCENARIO_IDS = (
    "ARRIVE_OFFICE",
    "OFFICE_LUNCH_OUT",
    "OFFICE_AFTERNOON",
    "LEAVE_OFFICE",
    "WEEKDAY_HOME_DAY",
    "ARRIVE_TRANSIT_HUB",
    "LATE_NIGHT_OVERTIME",
    "WEEKEND_OVERTIME",
    "EVENING_AT_OFFICE",
    "MORNING_EXERCISE",
    "SHOPPING",
    "HOME_EVENING",
    "ARRIVE_DINING",
    "HOME_LATE_NIGHT",
    "WEEKEND_MORNING",
    "WEEKEND_OUTING",
    "LATE_RETURN_HOME",
    "HOME_AFTERNOON",
    "MORNING_COFFEE",
    "GYM_WORKOUT",
    "GYM_REST",
    "GYM_LONG_STAY",
    "OUTDOOR_RUNNING",
    "WEEKEND_OUTDOOR_WALK",
    "CYCLING",
    "COMMUTE_MORNING",
    "COMMUTE_EVENING",
    "HOME_TO_GYM",
    "WAKE_UP",
    "PARK_WALK",
    "LONG_DRIVE",
    "CAFE_STAY",
    "QUIET_HOME",
    "NOISY_GATHERING",
    "LONG_OUTDOOR_WALK",
    "LATE_NIGHT_NOISY",
    "DELIVERY_AT_OFFICE",
    "EDUCATION_WAITING",
    "EDUCATION_LONG_SIT",
    "HOME_LUNCH",
    "AFTER_LUNCH_WALK",
    "MEETING_UPCOMING",
    "IN_MEETING",
    "REMOTE_MEETING",
    "NO_MEETINGS",
    "CAL_HAS_EVENTS",
    "RETURN_OFFICE_AFTER_LUNCH",
    "HOME_AFTER_GYM",
    "COMMUTE_FROM_HOME",
    "OFFICE_TO_CAFE",
    "LATE_NIGHT_PHONE",
    "OFFICE_FOCUS_LONG",
    "HOME_DARK_LONG",
    "UNKNOWN_LONG_STAY",
    "OFFICE_LONG_SESSION",
    "HOME_EVENING_DARK",
    "HOME_EVENING_NOISY",
    "SCHOOL_QUIET",
    "CAFE_QUIET",
    "TRAIN_DEPARTURE",
    "FLIGHT_BOARDING",
    "HOTEL_CHECKIN",
    "MOVIE_TICKET",
    "HOSPITAL_APPOINTMENT",
    "RIDESHARE_PICKUP",
    "unknown",
)

CANONICAL_STATE_CODES = (
    "home_sleeping",
    "home_morning_workday",
    "home_morning_rest",
    "home_daytime_workday",
    "home_daytime_rest",
    "home_evening",
    "home_active",
    "office_arriving",
    "office_lunch_break",
    "office_working",
    "office_overtime",
    "office_late_overtime",
    "office_rest_day",
    "commuting_walk_out",
    "commuting_walk_home",
    "commuting_cycle_out",
    "commuting_cycle_home",
    "commuting_drive_out",
    "commuting_drive_home",
    "commuting_transit_out",
    "commuting_transit_home",
    "driving",
    "in_transit",
    "at_metro",
    "at_rail_station",
    "at_airport",
    "at_transit_hub",
    "outdoor_walking",
    "outdoor_running",
    "outdoor_cycling",
    "outdoor_resting",
    "at_restaurant_lunch",
    "at_restaurant_dinner",
    "at_restaurant_other",
    "at_cafe",
    "at_gym_exercising",
    "at_gym",
    "at_shopping",
    "at_health",
    "at_social",
    "at_education",
    "at_custom",
    "stationary_unknown",
    "walking_unknown",
    "home_sleeping_lying",
    "home_morning_workday_lying",
    "home_morning_rest_lying",
    "home_daytime_workday_dark",
    "home_daytime_workday_lying",
    "home_daytime_rest_dark",
    "home_daytime_rest_lying",
    "home_evening_dark",
    "home_evening_lying",
    "home_evening_noisy",
    "office_working_focused",
    "office_working_noisy",
    "at_cafe_quiet",
    "at_education_class",
    "at_education_break",
    "at_health_inpatient",
    "unknown_noisy",
    "unknown_dark",
    "unknown_settled",
    "unknown_lying",
    "unknown",
)

LOCATION_CATEGORIES = (
    "home",
    "work",
    "restaurant",
    "cafe",
    "gym",
    "metro",
    "rail_station",
    "airport",
    "transit",
    "shopping",
    "outdoor",
    "health",
    "social",
    "education",
    "custom",
    "en_route",
    "unknown",
)

TIME_SLOTS = (
    "sleeping",
    "dawn",
    "morning",
    "forenoon",
    "lunch",
    "afternoon",
    "evening",
    "night",
    "late_night",
)

DAY_TYPES = ("workday", "weekend", "holiday")
MOTION_CATEGORIES = ("stationary", "walking", "running", "cycling", "driving", "transit", "unknown")
PHONE_CATEGORIES = ("in_use", "holding_lying", "on_desk", "face_up", "in_pocket", "face_down", "charging", "unknown")
SOUND_CATEGORIES = ("silent", "quiet", "normal", "noisy", "unknown")
NETWORK_TYPES = ("wifi", "cellular", "none")
TRANSPORT_MODES = ("walking", "running", "cycling", "driving", "transit", "stationary", "unknown")
ACTIVITY_STATES = ("sitting", "sleeping", "standing", "active", "unknown")
AGE_BUCKETS = ("0_17", "18_24", "25_34", "35_44", "45_54", "55_64", "65_plus", "unknown")
SEX_VALUES = ("female", "male", "other", "unknown")
USER_HASH_BUCKETS = tuple(f"b{i}" for i in range(32))
APP_CATEGORIES = ("social", "productivity", "entertainment", "navigation", "shopping", "news", "health", "music", "reading", "game")
