from __future__ import annotations

import json
import importlib.util
from pathlib import Path
import tempfile
import unittest

from recommendation_agents.schemas import ScoreRequest
from recommendation_agents.trainer import score_v0, train_v0


TORCH_AVAILABLE = importlib.util.find_spec("torch") is not None


@unittest.skipUnless(TORCH_AVAILABLE, "PyTorch is required for the training pipeline tests")
class TrainingPipelineTest(unittest.TestCase):
    def _write_fixture_files(self, tmp_dir: str) -> tuple[Path, Path]:
        metadata_path = Path(tmp_dir) / "metadata.json"
        samples_path = Path(tmp_dir) / "samples.jsonl"
        metadata = {
            "schema_version": "v0",
            "scenarios": [
                {
                    "scenario_id": "ARRIVE_OFFICE",
                    "default_action_id": "show_schedule",
                    "action_ids": ["show_schedule", "show_todo_list", "play_focus_music"],
                },
                {
                    "scenario_id": "HOME_EVENING",
                    "default_action_id": "show_family_todo",
                    "action_ids": ["show_family_todo", "play_relax_music", "show_weather"],
                },
                {
                    "scenario_id": "COMMUTE_MORNING",
                    "default_action_id": "show_commute_route",
                    "action_ids": ["show_commute_route", "show_calendar_brief", "read_news_digest"],
                },
            ],
            "actions": [
                {"action_id": "show_schedule", "display_name": "Show schedule"},
                {"action_id": "show_todo_list", "display_name": "Show todo list"},
                {"action_id": "play_focus_music", "display_name": "Play focus music"},
                {"action_id": "show_family_todo", "display_name": "Show family todo"},
                {"action_id": "play_relax_music", "display_name": "Play relax music"},
                {"action_id": "show_weather", "display_name": "Show weather"},
                {"action_id": "show_commute_route", "display_name": "Show commute route"},
                {"action_id": "show_calendar_brief", "display_name": "Show calendar brief"},
                {"action_id": "read_news_digest", "display_name": "Read news digest"},
            ],
        }
        samples = [
            {
                "event_id": "evt-001",
                "scenario_id": "ARRIVE_OFFICE",
                "context": {
                    "state_current": "office_arriving",
                    "state_duration_sec": 240,
                    "ps_time": "morning",
                    "hour": 9,
                    "cal_hasUpcoming": 1,
                    "ps_dayType": "workday",
                    "ps_motion": "stationary",
                    "wifiLost": 0,
                    "wifiLostCategory": "work",
                    "cal_eventCount": 4,
                    "cal_inMeeting": 0,
                    "cal_nextLocation": "work",
                    "ps_sound": "quiet",
                    "sms_delivery_pending": 0,
                    "sms_train_pending": 0,
                    "sms_flight_pending": 0,
                    "sms_hotel_pending": 0,
                    "sms_movie_pending": 0,
                    "sms_hospital_pending": 0,
                    "sms_ride_pending": 0,
                    "timestep": 32400,
                    "ps_location": "work",
                    "ps_phone": "on_desk",
                    "batteryLevel": 88,
                    "isCharging": 1,
                    "networkType": "wifi",
                    "transportMode": "stationary",
                    "activityState": "sitting",
                    "activityDuration": 1800,
                    "user_id_hash_bucket": "b3",
                    "age_bucket": "25_34",
                    "sex": "female",
                    "has_kids": 0,
                },
                "shown_actions": ["show_schedule", "show_todo_list", "play_focus_music"],
                "selected_action": "show_schedule",
                "reward": 1.0,
                "propensity": 0.85,
            },
            {
                "event_id": "evt-002",
                "scenario_id": "ARRIVE_OFFICE",
                "context": {
                    "state_current": "office_arriving",
                    "state_duration_sec": 180,
                    "ps_time": "morning",
                    "hour": 8,
                    "cal_hasUpcoming": 1,
                    "ps_dayType": "workday",
                    "ps_motion": "stationary",
                    "wifiLost": 0,
                    "wifiLostCategory": "work",
                    "cal_eventCount": 2,
                    "cal_inMeeting": 0,
                    "cal_nextLocation": "work",
                    "ps_sound": "normal",
                    "sms_delivery_pending": 0,
                    "sms_train_pending": 0,
                    "sms_flight_pending": 0,
                    "sms_hotel_pending": 0,
                    "sms_movie_pending": 0,
                    "sms_hospital_pending": 0,
                    "sms_ride_pending": 0,
                    "timestep": 30600,
                    "ps_location": "work",
                    "ps_phone": "face_up",
                    "batteryLevel": 72,
                    "isCharging": 0,
                    "networkType": "wifi",
                    "transportMode": "stationary",
                    "activityState": "standing",
                    "activityDuration": 300,
                    "user_id_hash_bucket": "b5",
                    "age_bucket": "35_44",
                    "sex": "male",
                    "has_kids": 1,
                },
                "shown_actions": ["show_schedule", "show_todo_list", "play_focus_music"],
                "selected_action": "show_schedule",
                "reward": 1.0,
                "propensity": 0.82,
            },
            {
                "event_id": "evt-003",
                "scenario_id": "ARRIVE_OFFICE",
                "context": {
                    "state_current": "office_arriving",
                    "state_duration_sec": 120,
                    "ps_time": "morning",
                    "hour": 9,
                    "cal_hasUpcoming": 0,
                    "ps_dayType": "workday",
                    "ps_motion": "stationary",
                    "wifiLost": 0,
                    "wifiLostCategory": "work",
                    "cal_eventCount": 0,
                    "cal_inMeeting": 0,
                    "cal_nextLocation": "unknown",
                    "ps_sound": "quiet",
                    "sms_delivery_pending": 0,
                    "sms_train_pending": 0,
                    "sms_flight_pending": 0,
                    "sms_hotel_pending": 0,
                    "sms_movie_pending": 0,
                    "sms_hospital_pending": 0,
                    "sms_ride_pending": 0,
                    "timestep": 33300,
                    "ps_location": "work",
                    "ps_phone": "in_use",
                    "batteryLevel": 91,
                    "isCharging": 0,
                    "networkType": "wifi",
                    "transportMode": "stationary",
                    "activityState": "active",
                    "activityDuration": 120,
                    "user_id_hash_bucket": "b7",
                    "age_bucket": "18_24",
                    "sex": "female",
                    "has_kids": 0,
                },
                "shown_actions": ["show_schedule", "show_todo_list", "play_focus_music"],
                "selected_action": "show_todo_list",
                "reward": 0.8,
                "propensity": 0.1,
            },
            {
                "event_id": "evt-004",
                "scenario_id": "HOME_EVENING",
                "context": {
                    "state_current": "home_evening",
                    "state_duration_sec": 2400,
                    "ps_time": "evening",
                    "hour": 19,
                    "cal_hasUpcoming": 0,
                    "ps_dayType": "workday",
                    "ps_motion": "stationary",
                    "wifiLost": 0,
                    "wifiLostCategory": "home",
                    "cal_eventCount": 0,
                    "cal_inMeeting": 0,
                    "cal_nextLocation": "unknown",
                    "ps_sound": "normal",
                    "sms_delivery_pending": 0,
                    "sms_train_pending": 0,
                    "sms_flight_pending": 0,
                    "sms_hotel_pending": 0,
                    "sms_movie_pending": 0,
                    "sms_hospital_pending": 0,
                    "sms_ride_pending": 0,
                    "timestep": 70200,
                    "ps_location": "home",
                    "ps_phone": "face_down",
                    "batteryLevel": 54,
                    "isCharging": 1,
                    "networkType": "wifi",
                    "transportMode": "stationary",
                    "activityState": "sitting",
                    "activityDuration": 2700,
                    "user_id_hash_bucket": "b9",
                    "age_bucket": "35_44",
                    "sex": "male",
                    "has_kids": 1,
                },
                "shown_actions": ["show_family_todo", "play_relax_music", "show_weather"],
                "selected_action": "show_family_todo",
                "reward": 1.0,
                "propensity": 0.8,
            },
            {
                "event_id": "evt-005",
                "scenario_id": "HOME_EVENING",
                "context": {
                    "state_current": "home_evening_noisy",
                    "state_duration_sec": 1800,
                    "ps_time": "evening",
                    "hour": 20,
                    "cal_hasUpcoming": 0,
                    "ps_dayType": "workday",
                    "ps_motion": "stationary",
                    "wifiLost": 0,
                    "wifiLostCategory": "home",
                    "cal_eventCount": 0,
                    "cal_inMeeting": 0,
                    "cal_nextLocation": "unknown",
                    "ps_sound": "noisy",
                    "sms_delivery_pending": 0,
                    "sms_train_pending": 0,
                    "sms_flight_pending": 0,
                    "sms_hotel_pending": 0,
                    "sms_movie_pending": 0,
                    "sms_hospital_pending": 0,
                    "sms_ride_pending": 0,
                    "timestep": 73800,
                    "ps_location": "home",
                    "ps_phone": "in_pocket",
                    "batteryLevel": 63,
                    "isCharging": 0,
                    "networkType": "wifi",
                    "transportMode": "stationary",
                    "activityState": "active",
                    "activityDuration": 1200,
                    "user_id_hash_bucket": "b9",
                    "age_bucket": "35_44",
                    "sex": "male",
                    "has_kids": 1,
                },
                "shown_actions": ["show_family_todo", "play_relax_music", "show_weather"],
                "selected_action": "play_relax_music",
                "reward": 0.7,
                "propensity": 0.12,
            },
            {
                "event_id": "evt-006",
                "scenario_id": "HOME_EVENING",
                "context": {
                    "state_current": "home_evening_dark",
                    "state_duration_sec": 3600,
                    "ps_time": "night",
                    "hour": 21,
                    "cal_hasUpcoming": 0,
                    "ps_dayType": "weekend",
                    "ps_motion": "stationary",
                    "wifiLost": 0,
                    "wifiLostCategory": "home",
                    "cal_eventCount": 1,
                    "cal_inMeeting": 0,
                    "cal_nextLocation": "home",
                    "ps_sound": "quiet",
                    "sms_delivery_pending": 0,
                    "sms_train_pending": 0,
                    "sms_flight_pending": 0,
                    "sms_hotel_pending": 0,
                    "sms_movie_pending": 1,
                    "sms_hospital_pending": 0,
                    "sms_ride_pending": 0,
                    "timestep": 77400,
                    "ps_location": "home",
                    "ps_phone": "holding_lying",
                    "batteryLevel": 41,
                    "isCharging": 0,
                    "networkType": "wifi",
                    "transportMode": "stationary",
                    "activityState": "sitting",
                    "activityDuration": 4200,
                    "user_id_hash_bucket": "b12",
                    "age_bucket": "25_34",
                    "sex": "female",
                    "has_kids": 0,
                },
                "shown_actions": ["show_family_todo", "play_relax_music", "show_weather"],
                "selected_action": "show_family_todo",
                "reward": 0.6,
                "propensity": 0.78,
            },
            {
                "event_id": "evt-007",
                "scenario_id": "COMMUTE_MORNING",
                "context": {
                    "state_current": "commuting_transit_out",
                    "state_duration_sec": 900,
                    "ps_time": "morning",
                    "hour": 8,
                    "cal_hasUpcoming": 1,
                    "ps_dayType": "workday",
                    "ps_motion": "transit",
                    "wifiLost": 1,
                    "wifiLostCategory": "home",
                    "cal_eventCount": 3,
                    "cal_inMeeting": 0,
                    "cal_nextLocation": "work",
                    "ps_sound": "normal",
                    "sms_delivery_pending": 0,
                    "sms_train_pending": 1,
                    "sms_flight_pending": 0,
                    "sms_hotel_pending": 0,
                    "sms_movie_pending": 0,
                    "sms_hospital_pending": 0,
                    "sms_ride_pending": 0,
                    "timestep": 29700,
                    "ps_location": "en_route",
                    "ps_phone": "face_up",
                    "batteryLevel": 76,
                    "isCharging": 0,
                    "networkType": "cellular",
                    "transportMode": "transit",
                    "activityState": "standing",
                    "activityDuration": 600,
                    "user_id_hash_bucket": "b3",
                    "age_bucket": "25_34",
                    "sex": "female",
                    "has_kids": 0,
                },
                "shown_actions": ["show_commute_route", "show_calendar_brief", "read_news_digest"],
                "selected_action": "show_commute_route",
                "reward": 1.0,
                "propensity": 0.78,
            },
            {
                "event_id": "evt-008",
                "scenario_id": "COMMUTE_MORNING",
                "context": {
                    "state_current": "commuting_drive_out",
                    "state_duration_sec": 1200,
                    "ps_time": "morning",
                    "hour": 8,
                    "cal_hasUpcoming": 1,
                    "ps_dayType": "workday",
                    "ps_motion": "driving",
                    "wifiLost": 1,
                    "wifiLostCategory": "home",
                    "cal_eventCount": 2,
                    "cal_inMeeting": 0,
                    "cal_nextLocation": "work",
                    "ps_sound": "normal",
                    "sms_delivery_pending": 0,
                    "sms_train_pending": 0,
                    "sms_flight_pending": 0,
                    "sms_hotel_pending": 0,
                    "sms_movie_pending": 0,
                    "sms_hospital_pending": 0,
                    "sms_ride_pending": 1,
                    "timestep": 30300,
                    "ps_location": "en_route",
                    "ps_phone": "face_up",
                    "batteryLevel": 68,
                    "isCharging": 0,
                    "networkType": "cellular",
                    "transportMode": "driving",
                    "activityState": "sitting",
                    "activityDuration": 1000,
                    "user_id_hash_bucket": "b14",
                    "age_bucket": "45_54",
                    "sex": "male",
                    "has_kids": 1,
                },
                "shown_actions": ["show_commute_route", "show_calendar_brief", "read_news_digest"],
                "selected_action": "show_calendar_brief",
                "reward": 0.6,
                "propensity": 0.15,
            },
            {
                "event_id": "evt-009",
                "scenario_id": "COMMUTE_MORNING",
                "context": {
                    "state_current": "commuting_walk_out",
                    "state_duration_sec": 600,
                    "ps_time": "morning",
                    "hour": 7,
                    "cal_hasUpcoming": 0,
                    "ps_dayType": "workday",
                    "ps_motion": "walking",
                    "wifiLost": 1,
                    "wifiLostCategory": "home",
                    "cal_eventCount": 1,
                    "cal_inMeeting": 0,
                    "cal_nextLocation": "work",
                    "ps_sound": "quiet",
                    "sms_delivery_pending": 0,
                    "sms_train_pending": 0,
                    "sms_flight_pending": 0,
                    "sms_hotel_pending": 0,
                    "sms_movie_pending": 0,
                    "sms_hospital_pending": 0,
                    "sms_ride_pending": 0,
                    "timestep": 27900,
                    "ps_location": "en_route",
                    "ps_phone": "in_pocket",
                    "batteryLevel": 92,
                    "isCharging": 0,
                    "networkType": "cellular",
                    "transportMode": "walking",
                    "activityState": "active",
                    "activityDuration": 480,
                    "user_id_hash_bucket": "b6",
                    "age_bucket": "18_24",
                    "sex": "other",
                    "has_kids": 0,
                },
                "shown_actions": ["show_commute_route", "show_calendar_brief", "read_news_digest"],
                "selected_action": "show_commute_route",
                "reward": 0.5,
                "propensity": 0.74,
            },
        ]
        metadata_path.write_text(json.dumps(metadata, indent=2, sort_keys=True))
        with samples_path.open("w") as handle:
            for sample in samples:
                handle.write(json.dumps(sample, sort_keys=True))
                handle.write("\n")
        return metadata_path, samples_path

    def _score_request(self) -> ScoreRequest:
        return ScoreRequest.from_dict(
            {
                "scenario_id": "ARRIVE_OFFICE",
                "context": {
                    "state_current": "office_arriving",
                    "state_duration_sec": 220,
                    "ps_time": "morning",
                    "hour": 9,
                    "cal_hasUpcoming": 1,
                    "ps_dayType": "workday",
                    "ps_motion": "stationary",
                    "wifiLost": 0,
                    "wifiLostCategory": "work",
                    "cal_eventCount": 3,
                    "cal_inMeeting": 0,
                    "cal_nextLocation": "work",
                    "ps_sound": "quiet",
                    "sms_delivery_pending": 0,
                    "sms_train_pending": 0,
                    "sms_flight_pending": 0,
                    "sms_hotel_pending": 0,
                    "sms_movie_pending": 0,
                    "sms_hospital_pending": 0,
                    "sms_ride_pending": 0,
                    "timestep": 32100,
                    "ps_location": "work",
                    "ps_phone": "on_desk",
                    "batteryLevel": 79,
                    "isCharging": 1,
                    "networkType": "wifi",
                    "transportMode": "stationary",
                    "activityState": "sitting",
                    "activityDuration": 1500,
                    "user_id_hash_bucket": "b7",
                    "age_bucket": "25_34",
                    "sex": "female",
                    "has_kids": 0,
                },
            }
        )

    def test_train_and_score_example_pipeline(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            metadata_path, samples_path = self._write_fixture_files(tmp_dir)

            metrics = train_v0(metadata_path, samples_path, tmp_dir)
            self.assertEqual(metrics.sample_count, 9)
            self.assertGreater(metrics.default_logged_action_rate, 0.5)

            request = self._score_request()
            ranked = score_v0(tmp_dir, metadata_path, request, top_k=3)
            self.assertEqual(len(ranked), 3)
            self.assertEqual(ranked[0].action_id, "show_schedule")

    def test_train_pipeline_records_cpu_device_by_default(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            metadata_path, samples_path = self._write_fixture_files(tmp_dir)
            train_v0(metadata_path, samples_path, tmp_dir)
            manifest = json.loads((Path(tmp_dir) / "manifest.json").read_text())
            self.assertEqual(manifest["device"], "cpu")

    def test_train_pipeline_accepts_explicit_cpu_device(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            metadata_path, samples_path = self._write_fixture_files(tmp_dir)
            train_v0(metadata_path, samples_path, tmp_dir, device="cpu")
            manifest = json.loads((Path(tmp_dir) / "manifest.json").read_text())
            self.assertEqual(manifest["device"], "cpu")


if __name__ == "__main__":
    unittest.main()
